art/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('', include('gallery.urls', namespace='gallery')),
    # url(r'^media/(?<path>.*)$', serve{'document_root':settings.MEDIA_ROOT}),
    # url(r'^static/(?<path>.*)$', serve{'document_root':settings.STATIC_ROOT}),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

gallery/urls.py
from django.urls import path
from . import views

app_name = 'gallery'
urlpatterns = [
    path('', views.art_list, name='art_list'),
    path('<slug:category_slug>/', views.art_list, name='art_list_by_category'),
    path('<int:id>/<slug:slug>/', views.art_detail, name='art_detail'),

    
]

gallery/models.py
from django.db import models
from django.urls import reverse
# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,unique=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('gallery:art_list_by_category', args=[self.slug])

class Art_Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('gallery:art_detail', args=[self.id, self.slug])

gallery/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Art_Product
from cart.forms import CartAddProductForm

# Create your views here.
def art_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Art_Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'gallery/art/index.html', {'category': category, 'categories': categories, 'products': products})

def art_detail(request, id, slug):
    product = get_object_or_404(Art_Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'gallery/art/product.html', {'product': product, 'cart_product_form': cart_product_form})

gallery/templates/gallery/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{% block title %}My shop{% endblock %}</title>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link href="{% static 'css/home.css' %}" rel="stylesheet">
<link href="{% static 'css/footer.css' %}" rel="stylesheet">
<link href="{% static 'css/base.css' %}" rel="stylesheet">
<link href="{% static 'css/product.css' %}" rel="stylesheet">
<link href="{% static 'css/cart.css' %}" rel="stylesheet">


</head>
<body>
  <nav class="navbar">
    <div class="nav">
      <img src="{% static "images/dark-logo.png" %}" class="brand-logo" alt="love">
      <div class="nav-items">
        <div class="search">
          <input type="text" class="search-box" placeholder="search 1place">
          <button class="search-btn">search</button>
          <a href="#"><img src="{% static "images/cart.png" %}" alt="add"></a>
        </div>
      </div>
    </div>
    <ul class="links-containers">
      <li {% if not category %}class="link-item"{% endif %}>
        <a href="{% url 'gallery:art_list' %}" class="link">All</a>
        </li>
        {% for c in categories %}
        <li {% if category.slug == c.slug %}class="link-item"
        {% endif %}><a href="{{ c.get_absolute_url }}" class="link">{{ c.name }}</a>
      </li>
      {% endfor %}
      <li class="link-item"><a href="" class="link">home</a></li>
      <li class="link-item"><a href="" class="link">home</a></li>
    </ul>
  </nav>

<!-- <div id="header">
<a href="/" class="logo">One Place</a>
</div>
<div id="subheader">
<div class="cart">
  {% with total_items=cart|length %}
  {% if total_items > 0 %}
  Your cart:
  <a href="{% url "cart:cart_detail" %}">
  {{ total_items }} item{{ total_items|pluralize }},
  ${{ cart.get_total_price }}
  </a>
  {% else %}
  Your cart is empty.
  {% endif %}
  {% endwith %}
<i class="fa fa-shopping-cart"></i>
</div>
</div>
<div id="content"> -->

 
{% block content %}
{% endblock %}
<footer>
  <div class="footer-content">
    <img src="{% static "images/light-logo.png" %}" class="logo" alt="">
   <div class="footer-ul-container">
    <ul class="category">
        <li class="category-title">men</li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
    </ul> 

    <ul class="category">
        <li class="category-title">women</li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
    </ul>

    <ul class="category">
        <li class="category-title">men</li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
        <li><a href="#" class="footer-link">jdjdjd</a></li>
    </ul>
</div>

</div>
<p class="footer-title">about oneplace</p>
<p class="info">Lorem ipsum dolor sit amet consectetur adipisicing elit. Deserunt aliquam repellat, laudantium perferendis veritatis soluta assumenda ea sapiente, quisquam modi obcaecati possimus laboriosam quae animi eos facilis exercitationem illum tempore cumque consequuntur architecto itaque. Obcaecati, cum quisquam. Quasi similique quaerat aperiam cumque iste exercitationem totam dicta, dolorum cupiditate suscipit, rerum quis consequatur excepturi tempore ullam eaque quos temporibus. Quod optio assumenda error dolorum, veritatis aliquam officia vel et, soluta qui totam a eius atque deserunt laudantium ex! Cupiditate aliquam assumenda fuga minus eius necessitatibus libero magni, aspernatur laudantium ducimus adipisci cumque ex natus rem perspiciatis excepturi mollitia, alias incidunt officiis.</p>
<p class="info">support email-example@gmail.com</p>
<p class="info">telephone-098234222383</p>
<div class="footer-social-container">
    <div>
        <a href="" class="social-links">terms & conditions</a>
        <a href="" class="social-links">privacy page</a>
    </div>
    <div>
        <a href="" class="social-links">facebook</a>
        <a href="" class="social-links">instagram</a>
        <a href="" class="social-links">twitter</a>
    </div>
</div>
<p class="footer-credit">oneplace, best art gallery online store</p>
</footer>
<script src="{% static 'js/product.js' %}"></script>
</body>
</html>